# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # environment: build-test-env
    env:
      PORT: ${{ secret.build-test-env.PORT }}
      MODE: ${{ secret.build-test-env.MODE }}
      USE_AUTH: ${{ secret.build-test-env.USE_AUTH }}
      APP_ORIGIN: ${{ secret.build-test-env.APP_ORIGIN }}
      LOCAL_APP_ORIGIN: ${{ secret.build-test-env.LOCAL_APP_ORIGIN }}
      LOCAL_APP_PORT: ${{ secret.build-test-env.LOCAL_APP_PORT }}
      AUTH0_AUDIENCE: ${{ secret.build-test-env.AUTH0_AUDIENCE }}
      AUTH0_ISSUER: ${{ secret.build-test-env.AUTH0_ISSUER }}
      AUTH0_ALGORYTHM: ${{ secret.build-test-env.AUTH0_ALGORYTHM }}
      DB_CONNECT: ${{ secret.build-test-env.DB_CONNECT }}
      SESSION_SECRET: ${{ secret.build-test-env.SESSION_SECRET }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run test
      - run: npm run build
